### ISSUE TITLE
Trackwork on server is bugged and crashes sometimes after a short time. 1.20.1 v1.0.1beta on Forge

### ISSUE THREAD

**Issue by Billnotic** [Endalion/trackwork#12]
HERE IS AN EXAMPLE PORTION OF THE SERVER LOG:
[07Sep2024 05:21:40.369] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: Error in physics pipeline background task
java.lang.NullPointerException: Cannot read field "trackPos" because "data" is null
	at edn.stratodonut.trackwork.tracks.data.PhysEntityTrackData.from(PhysEntityTrackData.java:60) ~[trackwork-1.20.1-1.0.1-beta.jar%23702!/:1.20.1-1.0.1-beta]
	at edn.stratodonut.trackwork.tracks.forces.PhysEntityTrackController.applyForcesAndLookupPhysShips(PhysEntityTrackController.java:64) ~[trackwork-1.20.1-1.0.1-beta.jar%23702!/:1.20.1-1.0.1-beta]
	at org.valkyrienskies.core.impl.shadow.Aq.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23707!/:?]
	at org.valkyrienskies.core.impl.shadow.At.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23707!/:?]
	at org.valkyrienskies.core.impl.shadow.Ap.run(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23707!/:?]
	at org.valkyrienskies.core.impl.shadow.At$1.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23707!/:?]
	at org.valkyrienskies.core.impl.shadow.At$1.invoke(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23707!/:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[kotlinforforge-4.10.0-all.jar%23604!/:?]
[07Sep2024 05:21:40.370] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
(message sent 8 more times in the log lol)
[07Sep2024 05:21:40.371] [Physics thread/WARN] [org.valkyrienskies.core.impl.shadow.Ap/]: Physics pipeline ending

HERE IS A CRASH REPORT:
https://api.mclo.gs/1/raw/HYtkfoV

**Comment by blockninja124** [comment]
This crash specifically happens when Billnotic pastes in a specific tank schematic. The schematic itself is here: (from the discord [here]())

**Comment by Billnotic** [comment]
Got around to downloading a backup of the server I was on and testing on it. I think I may have found a cause but am not 100% certain.

Infusing physics into a structure with belts makes the belts appear bugged, and with or without replacing them the physics object will occasionally crash the VS physics thread due to a null track for some reason. Infusing and then adding belts creates an object which does not crash.
I still need to test this more thoroughly as this conclusion came from very little data and also doesn't make any sense as there is no reason this would affect Trackwork but its all I have so far.

**Comment by Billnotic** [comment]
NVM still broken.

**Comment by Endalion** [comment]
@Billnotic can you test for this on the latest version?

**Comment by Endalion** [comment]
Closing stale issue
